brainstormforce/astra-sites

- inc/classes/class-astra-sites-white-label.php
- inc/classes/class-astra-sites.php
- inc/templates/white-label.php
Adds white label settings in the white label settings panel from Astra Pro
> White label support

- README.md
- astra-sites.php
- inc/assets/js/render-grid.js
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites-notices.php
- inc/classes/class-astra-sites-page.php
- inc/classes/class-astra-sites-white-label.php
- inc/classes/class-astra-sites.php
- inc/classes/compatibility/elementor/class-astra-sites-compatibility-elementor.php
- inc/classes/compatibility/elementor/class-astra-sites-source-remote.php
- inc/importers/class-astra-sites-helper.php
- inc/importers/wxr-importer/class-astra-wxr-importer.php
- inc/includes/admin-page.php
- inc/includes/white-label.php
- readme.txt
Now, Initially We list 6 Astra sites. On large screen it looks like we have only 6 sites. Now, We have initially showing 15 sites.
> Loading 15 sites instead of 6 on Astra Sites page.

- README.md
- astra-sites.php
- inc/assets/css/admin.css
- inc/assets/js/admin-page.js
- inc/assets/js/astra-sites-notices.js
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites-notices.php
- inc/classes/class-astra-sites.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- inc/classes/compatibility/woocommerce/class-astra-sites-compatibility-woocommerce.php
- inc/importers/class-astra-site-options-import.php
- languages/astra-sites.pot
- readme.txt
* Improvement: Importing WooCommerce product category images.
* Improvement: Retain WooCommerce cart, checkout & my account pages when importing the ready WooCommerce sites.
* Fix: Disabled WooCommerce plugin setup wizard after plugin install & activate.
> Woocommerce product category images & pages support.

- README.md
- astra-sites.php
- inc/assets/css/admin.css
- inc/includes/admin-page.php
- languages/astra-sites.pot
- readme.txt
- Fix: String `Select Your Favorite Page Builder` jerk while loading the sites.
> Release v1.1.9

- README.md
- astra-sites.php
- inc/importers/batch-processing/class-astra-sites-batch-processing-elementor-v2.php
- inc/importers/batch-processing/class-astra-sites-batch-processing-elementor.php
- inc/importers/batch-processing/class-astra-sites-batch-processing.php
- languages/astra-sites.pot
- phpcs.xml.dist
- readme.txt
* Improvement: Added compatibility for Elemetor version 2.0.0. Older versions throw the PHP warnings.
> Elementor v2 compatibility

- README.md
- astra-sites.php
- inc/classes/class-astra-sites-importer.php
- languages/astra-sites.pot
- readme.txt
- Improvement: Regenerate the Astra Pro plugin cache after site import.
> Release v1.2.1  

- Gruntfile.js
- README.md
- astra-sites.php
- inc/importers/batch-processing/class-astra-sites-batch-processing.php
- languages/astra-sites.pot
- package-lock.json
- readme.txt
- Correctly load the elementor pro 2.0 class when the version of elementor pro is higher than 2.0.0-beta1
> Support for Elementor 2.0

- inc/classes/class-astra-sites.php
- readme.txt
Added the support for EDGE browser.
> Improvement: Astra Sites not importing in Window EDGE browser.

- README.md
- astra-sites.php
- inc/assets/js/render-grid.js
- inc/includes/admin-page.php
- languages/astra-sites.pot
- readme.txt
- Improvement: Removed custom license validation form and used Graupi in-build license validation form.
- Improvement: Set default page builders depends on the packaged purchase.
> Release v1.2.4

- README.md
- astra-sites.php
- inc/assets/css/admin.css
- inc/assets/js/render-grid.js
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
- languages/astra-sites.pot
- readme.txt
* Improvement: Added page builder and category filter support to show selected page builder with selected categories.
* Improvement: Added filter `astra_sites_show_filters` to enable/disable the filter list from admin page.
> Release v1.2.7

- astra-sites.php
- readme.txt
Updated plugin name and description
> Updated plugin name and dscription

- README.md
- astra-sites.php
- inc/assets/css/admin.css
- inc/includes/admin-page.php
- languages/astra-sites.pot
- readme.txt
Improvement: Set the max height for the website image from the website preview window.
> Release v1.3.1

- README.md
- astra-sites.php
- inc/assets/css/admin.css
- inc/assets/js/admin-page.js
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Improvement: Added compatibility for WP Forms pro version.
- Fix: PHP error while importing customizer settings.
> Release v1.3.3

- README.md
- astra-sites.php
- inc/importers/batch-processing/class-astra-sites-batch-processing.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Improvement: Added compatibility for below WordPress 5.1.
> Release 1.3.12

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Improvement: Added Support for Learndash WooCommerce integration plugin.
> Release v1.3.14

- README.md
- astra-sites.php
- inc/assets/js/admin-page.js
- languages/astra-sites.pot
- package.json
- readme.txt
- Fix: Importing pages, post twice from the import process.
> Release v1.3.15

- README.md
- astra-sites.php
- inc/importers/class-astra-site-options-import.php
- package.json
- readme.txt
-  Improvement: Added missing font awesome icons support for the Elementor sites.
> Release v1.4.5

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- languages/astra-sites.pot
- package-lock.json
- package.json
- readme.txt
- Improvement: Minor code changes.
> Release v2.3.3

- README.md
- astra-sites.php
- inc/assets/css/astra-notices-rtl.css
- inc/assets/css/astra-notices.css
- inc/assets/images/logo.svg
- inc/assets/js/admin-page.js
- inc/classes/class-astra-sites.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Improvement: Added the Pixabay images support for new post, pages, and custom post type screen.
- Improvement: Added the 5 star rating notice.
- Improvement: Showing the sync fail notice with error.
> Release v2.3.6

- README.md
- astra-sites.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- inc/classes/compatibility/learndash/class-astra-sites-compatibility-learndash.php
- inc/importers/wxr-importer/class-astra-wxr-importer.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Fix: LearnDash grid CSS not loading after site import.
> Release v2.3.8

- inc/includes/admin-page.php
https://trello.com/c/GpwfG40v/155-delete-previously-imported-site
> fix: conditionally show delete previously imported sites option

- inc/classes/functions.php
- inc/includes/admin-page.php
- inc/includes/templates.php
https://trello.com/c/rszugCij/182-improvement-for-suggestion-link-in-astra-sites-premium-sites
> fix: improved suggestion link

- inc/importers/batch-processing/class-astra-sites-batch-processing.php
https://trello.com/c/9FUOnVzm/190-mention-option-names-while-updateing-the-json-files
> Fix: avoided dynamic json file names for importing

- inc/assets/js/admin-page.js
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
https://trello.com/c/UEAZyYMO/214-show-deleted-site-option-with-ajax
> fix: delete previously imported sites option on first import

- inc/assets/js/admin-page.js
- inc/includes/admin-page.php
https://trello.com/c/L5IeExoj/220-arrow-position-ui-improvement
> improvement: advance option arrow UI

- inc/classes/class-astra-sites-importer.php
- inc/classes/functions.php
- inc/importers/batch-processing/class-astra-sites-batch-processing-gutenberg.php
- inc/importers/batch-processing/helpers/class-astra-sites-image-importer.php
- inc/importers/class-astra-customizer-import.php
- inc/importers/class-astra-sites-helper.php
- inc/importers/wxr-importer/class-wxr-importer.php
https://trello.com/c/FBH242Kh/227-add-svg-image-support
> fix: added svg support for image

- inc/includes/admin-page.php
https://starter-templates.atlassian.net/jira/software/projects/ST/boards/5?selectedIssue=ST-121
> fix: upload directory hidden for white-labelled

- astra-sites.php
- inc/classes/class-astra-sites.php
- inc/lib/bsf-quick-links/class-bsf-quick-links.php
- inc/lib/bsf-quick-links/quicklink.css
- inc/lib/bsf-quick-links/quicklinks.js
- inc/lib/bsf-quick-links/readme.md
https://trello.com/c/5NL5YLTX/212-add-quick-links-popup
> feat: added quick links

- inc/classes/class-astra-sites.php
https://trello.com/c/fuMQIv20/218-wpscriptslocalize-was-called-incorrectly
> fix:script localization was called incorrectly

- inc/assets/js/admin-page.js
https://starter-templates.atlassian.net/browse/ST-67
> fix: prevent clicking on button while importing.

- inc/assets/js/admin-page.js
Event called twice was removed
> fix: removed duplicate event call

- inc/assets/js/admin-page.js
- inc/includes/admin-page.php
Test Cases - 
1. - Install Free Starter Templates on a fresh setup
2. - Import Outdoor Adventure Template
3. - Submit the subscription form and complete the importing.
4. - Once the import is completed click on Import Site Button without refreshing the page.
5. - Bug: You will see Subscription form again
---
1. Install Free Starter Templates on a fresh setup
2. Import Outdoor Adventure Template
3. Submit the subscription form and complete the importing.
4. Once the import is completed go to search box and search learndash click on the template
5. Now click on Import Site button
6. Bug: You will see Subscription form again
---
Install Free Starter Templates on a fresh setup
Import Outdoor Adventure Template
Submit the subscription form and complete the importing.
Once the import is …
> ST-188 - fix: subscription form shown again even it is subscribed once

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
- inc/lib/ast-block-templates/classes/class-ast-block-templates.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Removed unwanted escaping 
- Added better error messages
> Fix: Avoided the HTML being printed on screen

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- package.json
- readme.txt
Fix: Fatal Error number of arguments incorrect on Starter Templates main page.
Steps to Reproduce:
1. Reset WP
2. Install latest Starter Template
3. Go to Starter Template page and you will see the fatal error.
Screenshot: [https://share.bsf.io/yAurGyP7](https://share.bsf.io/yAurGyP7)
> fix: Fatal Error number of arguments incorrect on Starter Templates main page.

- .github/workflows/release-pr-template.yml
Added release checklist workflow
> Release checklist workflow

- inc/classes/class-astra-sites-page.php
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
Pricing page URL updated to https://wpastra.com/starter-templates-plans/
> chore: Pricing page url updated

- README.md
- astra-sites.php
- inc/assets/css/admin-rtl.css
- inc/assets/css/elementor-admin-rtl.css
- package.json
- readme.txt
Updated changelog and version to `2.6.13`
> RC- Changelog update and version bump

- README.md
- inc/classes/functions.php
- inc/lib/ast-block-templates/classes/class-ast-block-templates.php
- inc/lib/astra-notices/class-astra-notices.php
- languages/astra-sites.pot
- readme.txt
v2.6.14 - 13-July-2021
- Improvement: Compatibility to WordPress 5.8.
- Improvement: Improved the import process by reducing the body size of the AJAX calls for better performance.
- Improvement: Added support for dark and light support for block patterns with improved sidebar UI.
- Fix: Handle the white label support.
> ST-250 - chore: updated changelog

- inc/classes/class-astra-sites.php
Upgrade link updated with UTM parameters.
Link updated to - `https://wpastra.com/starter-templates-plans/?utm_source=StarterTemplatesPlugin&utm_campaign=WPAdmin`
> ST-249 - chore: upgrade link updated with UTM parameters

- .github/workflows/ci.yml
- README.md
- astra-sites.php
- languages/astra-sites.pot
- package.json
- readme.txt
> Build: Release PR Update preparation

- assets/js/admin.js
- classes/class-astra-sites-admin.php
- inc/assets/js/admin-page.js
- inc/assets/js/dist/main.asset.php
- inc/classes/batch-import/class-astra-sites-batch-site-import.php
- inc/classes/class-astra-sites.php
- inc/includes/admin-page.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
Added different landing page links.
Yes. Manually.
> Updated the quick links

- README.md
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- readme.txt
> Updated release date.

- README.md
- astra-sites.php
- inc/assets/js/admin-page.js
- inc/assets/js/dist/main.asset.php
- inc/classes/class-astra-sites.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- languages/astra-sites.pot
- readme.txt
Improvement: Displaying 500 errors on the import screen.
> Pre release

- inc/importers/batch-processing/class-astra-sites-batch-processing.php
Action added for saving templates count as per page builder
> STS-23 - fix: action added for saving templates count 

- inc/classes/class-astra-sites.php
Added filter `starter_templates_elementor_button` to disable/remove Starter templates popup button from Elementor editor.
> ST-223 - Added filter `starter_templates_hide_elementor_button`

- inc/classes/class-astra-sites-importer.php
- inc/lib/onboarding/assets/src/steps/survey/style.scss
- inc/lib/onboarding/assets/src/steps/survey/survey.js
latest changes for survey form design and duplication pages
> chore: latest changes for survey form design and duplication pages

- inc/classes/compatibility/woocommerce/class-astra-sites-compatibility-woocommerce.php
- inc/lib/onboarding/assets/src/steps/congrats/style.scss
- inc/lib/onboarding/assets/src/steps/welcome/index.js
- inc/lib/onboarding/assets/src/steps/welcome/style.scss
- inc/lib/onboarding/assets/src/style.scss
- inc/lib/onboarding/classes/class-astra-sites-ai-site-setup.php
> chore: latest changes pull

- .github/workflows/push-to-deploy.yml
> Removed package creation step from WP deployment

- README.md
- astra-sites.php
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites.php
- inc/classes/functions.php
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- inc/lib/onboarding/assets/src/store/reducer.js
- inc/lib/onboarding/classes/class-astra-sites-ai-site-setup.php
- languages/astra-sites.pot
- package.json
- readme.txt
> Release ready

- astra-sites.php
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- languages/astra-sites.pot
- package.json
- readme.txt
v3.0.4 - 8-December-2021
Fix: Log the errors reported on the posts delete step during deleting old site.
> Release 3.0.4

- astra-sites.php
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- package.json
- readme.txt
Fix: Import process stopping after the posts are deleted.
> Version 3.0.5

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- inc/lib/onboarding/assets/src/components/error/index.js
- inc/lib/onboarding/assets/src/components/error/style.scss
- inc/lib/onboarding/assets/src/steps/customize-site/customize-steps/license-validation/controls.js
- inc/lib/onboarding/assets/src/steps/import-site/import-utils.js
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- inc/lib/onboarding/assets/src/utils/functions.js
- inc/lib/onboarding/class-onboarding-loader.php
- languages/astra-sites.pot
- package.json
- readme.txt
- Fix: Fixed an issue with import failure when the user activates the license for the first time.
- Fix: Fixed the errors on the final import step.
> v3.0.7 release

- .distignore
- package.json
- webpack.config.js
- Build RTL CSS file with webpack build
- Ignore eslintrc and eslintignore
Bug fix (non-breaking change which fixes an issue)
> Generate RTL css build files

- README.md
- astra-sites.php
- inc/classes/class-astra-sites.php
- inc/lib/onboarding/assets/src/components/media-uploader/index.js
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- inc/lib/onboarding/assets/src/steps/survey/index.js
- inc/lib/onboarding/assets/src/steps/survey/style.scss
- inc/lib/onboarding/assets/src/style.scss
- package.json
- readme.txt
- Improvement: Better error handling for Fatal errors.
- Improvement: Added a pre-requisite screen before the import process.
- Fix: Fixed a few RTL support issues for the entire import process.
> v3.0.13 release

- README.md
- astra-sites.php
- inc/classes/class-astra-sites-image-processing.php
- inc/classes/class-astra-sites.php
- inc/classes/compatibility/beaver-builder/class-astra-sites-compatibility-bb.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- inc/classes/functions.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- inc/lib/onboarding/assets/src/steps/site-list/site-category-filter/index.js
- inc/lib/onboarding/assets/src/steps/survey/index.js
- inc/lib/onboarding/class-onboarding-loader.php
- inc/lib/onboarding/classes/class-astra-sites-onboarding-setup.php
- package.json
- readme.txt
- Fix: Avoided redirection for Beaver Builder plugin when activated from import screen.
- Fix: Resolved a few errors with the pre-import PHP compatibility screen.
> v3.0.21 release

- README.md
- astra-sites.php
- inc/classes/class-astra-sites-error-handler.php
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- inc/classes/compatibility/uabb/class-astra-sites-compatibility-uabb.php
- inc/importers/batch-processing/class-astra-sites-batch-processing.php
- inc/lib/onboarding/assets/src/steps/import-site/index.js
- inc/lib/onboarding/assets/src/steps/site-list/header/sync-library/index.js
- inc/lib/onboarding/assets/src/steps/site-list/header/sync-library/utils.js
- inc/lib/onboarding/assets/src/steps/site-list/index.js
- inc/lib/onboarding/assets/src/steps/survey/index.js
- inc/lib/onboarding/assets/src/store/reducer.js
- inc/lib/onboarding/assets/src/utils/search.js
- languages/astra-sites.pot
- package.json
- readme.txt
- Fix: Better error and exception handling while importing.
- Fix: Fixed an issue with redirection while installing Ultimate Addons for Beaver Builder - Lite plugin.
- Fix: Fixed an issue where the templates library won't refresh in real-time after the sync process.
- Fix: Presto Player installation showing PHP incompatibility notice while importing a template.
> v3.0.23 release

- README.md
- Updated plugin readme file of ST 3.0
> ST-869 - Updated plugin readme file of ST 3.0

- README.md
- astra-sites.php
- inc/assets/js/elementor-admin-page.js
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites.php
- inc/classes/functions.php
- inc/importers/batch-processing/class-astra-sites-batch-processing-widgets.php
- inc/importers/batch-processing/class-astra-sites-batch-processing.php
- inc/importers/batch-processing/helpers/class-wp-background-process-astra-single.php
- inc/importers/batch-processing/helpers/class-wp-background-process-astra.php
- inc/lib/class-astra-sites-ast-block-templates.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- inc/lib/onboarding/assets/src/components/media-uploader/index.js
- inc/lib/onboarding/assets/src/components/media-uploader/style.scss
- inc/lib/onboarding/assets/src/steps/customize-site/customize-steps/business-logo/controls.js
- inc/lib/onboarding/assets/src/steps/site-list/index.js
- inc/lib/onboarding/assets/src/steps/site-list/sites-grid/index.js
- package-lock.json
- package.json
- readme.txt
- Fix: Fixed an issue with retina logo image download during import.
- Fix: Fixed an issue with WP Forms not being imported when used in the footer of the website.
- Fix: Fixed a console error in some cases where the template took longer to fetch its contents.
> v3.1.3 release

- README.md
- astra-sites.php
- inc/classes/compatibility/checkout-plugins-stripe-woo/class-astra-sites-checkout-plugins-stripe-woo.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- inc/importers/batch-processing/class-astra-sites-batch-processing-gutenberg.php
- inc/lib/gutenberg-templates/classes/class-ast-block-templates.php
- languages/astra-sites.pot
- package.json
- readme.txt
Improvement: Enhanced test environment
Fix: Fixed redirection of few required plugins during import.
> Version 3.1.9

- .github/workflows/push-to-deploy.yml
> imprv: updated github actions

- README.md
- astra-sites.php
- package.json
- readme.txt
> fix: pre release steps

- admin/bsf-analytics/class-bsf-analytics-stats.php
- admin/bsf-analytics/class-bsf-analytics.php
- admin/bsf-analytics/version.json
> Update BSF analytics version to 1.1.3

- inc/lib/onboarding/assets/src/steps/survey/advanced-settings.js
Installed required plugin checkbox enabled when a plugin needs to install
> Installed required plugin checkbox enabled when a plugin needs to install

- composer.json
> Allow dealerdirect/phpcodesniffer-composer-installer package to composer config

- README.md
- astra-sites.php
- composer.lock
- inc/lib/astra-notices/class-astra-notices.php
- package-lock.json
- package.json
- readme.txt
---
---
Improvement: Disable promotes Essential & Growth bundle when the white label is enabled.
Fix: Templates are not displayed when we install the plugin from Astra notice.
Fix: Display "Install Required Plugins" checkbox option if required plugins are remaining to install.
Reference: https://github.com/brainstormforce/astra-pro-sites/pull/772
> Build: Release PR Pre-release v3.1.12

- inc/classes/compatibility/elementor/class-astra-sites-compatibility-elementor.php
> disabled-elementor-redirect

- inc/importers/wxr-importer/class-wxr-importer.php
Skip trash OR draft OR dp-rewrite-republish posts while importing site
> Skip trash posts while importing site

- README.md
- astra-sites.php
- package-lock.json
- package.json
- readme.txt
> Build: Release PR Pre-release v3.1.14

- inc/classes/class-astra-sites.php
- inc/lib/onboarding/assets/src/steps/site-list/search-filter/index.js
- inc/lib/onboarding/assets/src/store/reducer.js
> STAR-56 - Draft Sites able to be searched from search input

- README.md
- astra-sites.php
- composer.lock
- inc/classes/class-astra-sites-importer.php
- inc/classes/class-astra-sites.php
- package-lock.json
- package.json
- readme.txt
> Build: Release PR Pre-release v3.1.16

- assets/css/astra-notices.css
> STAR-79 - WP Welcome banner Responsive

- inc/importers/class-astra-site-options-import.php
> Fix WP6.1 compatibility issue

- README.md
- readme.txt
> Tested up to wp 6.1

- inc/classes/class-astra-sites-page.php
https://brainstormforce.atlassian.net/browse/STAR-86
> STAR-86 - Missed function added for select page builder using  WP-CLI

- README.md
- astra-sites.php
- package-lock.json
- package.json
- readme.txt
> Build: Release PR Pre release 3.1.19

- inc/importers/wxr-importer/class-astra-wxr-importer.php
> Fix PHP8 compatibility

- inc/classes/class-astra-sites.php
- inc/lib/onboarding/assets/src/steps/site-list/sites-grid/index.js
Added extra checks while marking a Starter Template as favorite
> Added extra checks while marking a Starter Template as favorite

- inc/classes/class-astra-sites.php
> Remove PHPCS:Ignore

- README.md
- astra-sites.php
- package-lock.json
- package.json
- readme.txt
> Build: Release PR PR Pre release 3.1.21

- Gruntfile.js
- README.md
- astra-sites.php
- inc/classes/class-astra-sites-importer.php
- package.json
- readme.txt
Plugin installation from WordPress plugins dashboard fails when Starter Template is activated.
> Release candidate v3.1.26

- README.md
- astra-sites.php
- inc/lib/onboarding/assets/src/steps/site-list/header/sync-library/utils.js
- package.json
- readme.txt
> Fix: Templates library won't refresh after the sync process due to invalid nonce

- README.md
- astra-sites.php
- inc/classes/class-astra-sites-importer.php
- inc/lib/onboarding/assets/src/steps/site-list/header/sync-library/utils.js
- package.json
- readme.txt
> Release candidate v3.1.27

- inc/assets/css/elementor-admin-rtl.css
- inc/assets/css/elementor-admin.css
- https://brainstormforce.slack.com/archives/C7B1NJNF8/p1680189145775689
- https://d.pr/v/bGDRHm
> fix: ST button background on Elementor editor

- inc/lib/onboarding/assets/src/steps/import-site/index.js
> Fix: Backup json file not created

- README.md
> Tested up to updated

- README.md
- readme.txt
> Version date updated

- README.md
- astra-sites.php
- package.json
- readme.txt
> Pre release v3.2.1

- README.md
- inc/lib/onboarding/assets/src/components/choose-ecommerce/style.scss
- readme.txt
> Changelog updated

- readme.txt
> Updated 6.3 WP compatibility test

- README.md
- inc/classes/compatibility/cartflows/class-astra-sites-compatibility-cartflows.php
- inc/classes/compatibility/class-astra-sites-compatibility.php
- readme.txt
> Added Cartflows compatibility and version update
