README.md, astra-sites.php, inc/classes/class-astra-sites-importer.php, inc/classes/compatibility/astra-pro/class-astra-sites-compatibility-astra-pro.php, inc/importers/class-astra-site-options-import.php, inc/importers/class-astra-sites-helper.php, inc/importers/wxr-importer/class-astra-wxr-importer.php, languages/astra-sites.pot, readme.txt
```
* New: Added filter `astra_sites_xml_import_options` to change the XML import options.
* Fix: Astra Pro plugin 'Custom Layouts' & 'Page Headers' not setting right display location due to different page, tax, category ids.
* Fix: WooCommerce shop, checkout cart page ids not setting issue.
```
=> Release v1.1.6

README.md, astra-sites.php, inc/classes/class-astra-sites-importer.php, inc/classes/compatibility/astra-pro/class-astra-sites-compatibility-astra-pro.php, inc/importers/batch-processing/class-astra-sites-batch-processing-misc.php, inc/importers/batch-processing/class-astra-sites-batch-processing.php, inc/importers/class-astra-site-options-import.php, inc/importers/class-astra-sites-helper.php, inc/importers/wxr-importer/class-astra-wxr-importer.php, readme.txt
Changelog:
* New: Added filter `astra_sites_xml_import_options` to change the XML import options.
* Fix: Astra Pro plugin 'Custom Layouts' & 'Page Headers' not setting right display location due to different page, tax, category ids.
* Fix: WooCommerce shop, checkout cart page ids not setting issue.
* Fix: After site import updated demo url from the nav menus.
=> Release 1.1.6

inc/assets/css/admin.css, inc/includes/admin-page.php
- Used WordPress dashicon arrow instead of HTML entity in select page builder string.
- Change the site type string from `premium` with `agency`.
=> Change the site type string from premium with agency.

inc/classes/class-astra-sites-importer-log.php, inc/classes/compatibility/astra-pro/class-astra-sites-compatibility-astra-pro.php, readme.txt
* Fix: Clear the Astra Pro plugin cache after site import.
* Improvement: The log file was not created if server does not support the file handling functions.
=> File handling and Astra Pro plugin cache fixes

README.md, astra-sites.php, inc/importers/wxr-importer/class-astra-wxr-importer.php, languages/astra-sites.pot, readme.txt
* Fix: We have added `wp_slash` to normalize the Elementor post meta. Elementor have also normalize it. So, We have avoided `wp_slash` while importing sites.
=> Release v1.2.6

astra-sites.php, inc/classes/class-astra-sites-importer-log.php, inc/classes/class-astra-sites-importer.php, inc/classes/class-astra-sites-page.php, inc/classes/class-astra-sites-white-label.php, inc/classes/class-astra-sites.php, inc/classes/compatibility/astra-pro/class-astra-sites-compatibility-astra-pro.php, inc/importers/batch-processing/class-astra-sites-batch-processing-gutenberg.php, inc/importers/class-astra-site-options-import.php, inc/importers/class-astra-sites-helper.php, inc/importers/wxr-importer/class-astra-wxr-importer.php, languages/astra-sites.pot, package.json, readme.txt
Test Case - 
1) Assigned Category (say "Travel") to UAG  Post Grid block.
2) Import the website.
3) The Page containing this block did not have the category ("Travel") retained.
=>  * Fix: After Import UAG - Post Grid categories do not retain issue fixed

inc/importers/class-astra-sites-helper.php
Restores the timeout time to be 300 seconds which is the default for `download_url()`
=> Change timeout for downloading the XML file

README.md, astra-sites.php, inc/classes/class-astra-sites-importer.php, inc/classes/class-astra-sites-wp-cli.php, inc/classes/class-astra-sites.php, inc/classes/compatibility/class-astra-sites-compatibility.php, inc/classes/compatibility/elementor/class-astra-sites-compatibility-elementor.php, inc/classes/compatibility/sfwd-lms/class-astra-sites-compatibility-sfwd-lms.php, inc/importers/batch-processing/class-astra-sites-batch-processing.php, inc/importers/batch-processing/helpers/class-astra-sites-image-importer.php, languages/astra-sites.pot, package-lock.json, package.json, readme.txt
- Fix: Installing premium plugin from the WP CLI import.
- Fix: WP CLI command `wp astra-sites list` showing the old result.
- Fix: PHP error Astra_Sites_Batch_Processing_Elementor does not exist from WP CLI import.
- Improvement: Some Elementor templates broken due to the missing wp_slash() from WP CLI import.
=> Release v1.4.3

README.md, astra-sites.php, inc/assets/js/render-grid.js, inc/classes/class-astra-sites-importer-log.php, inc/classes/class-astra-sites.php, languages/astra-sites.pot, package.json, readme.txt
- Improvement: Added the old browser compatibility in which Astra Sites not loading.
- Improvement: Used `gmdate()` function instead of `date()` which affected by runtime timezone changes.
=> Release v1.4.4

inc/assets/css/admin-rtl.css, inc/assets/css/admin.css, inc/assets/css/elementor-admin-rtl.css, inc/assets/css/elementor-admin.css, inc/assets/css/images-rtl.css, inc/assets/css/images.css, inc/assets/js/dist/index.js, inc/assets/js/src/frame.js, inc/classes/class-astra-sites-page.php, inc/classes/class-astra-sites.php, inc/includes/admin-page.php, inc/includes/image-templates.php, inc/includes/templates.php
Recently we have used CSS class `icon-*` which create conflict with other plugins and themes. Now, we have added the `ast-` prefix for all the icon font CSS classes. 
Manually tested.
=> Added the ast- prefix for all icon fonts.

README.md, readme.txt
Changelog updated to - 
- Improvement: Used better and optimised way to show the initial sites and pages list on Starter Template dashboard.
- Improvement: Block Templates - Used version.json instead of package.json to manage the dependency.
- Improvement: Block Templates - Now users can suggest their required templates via suggestion link.
- Improvement: Block Templates - Added filter to disable the Block Templates. - https://wpastra.com/docs/filter-to-remove-starter-templates-button/
- Fix: Block Templates - Retained the selected block pattern category filter after switching between Pages/Patterns tabs.
- Fix: Rectified the invisible icon from the 'View Site' button.
- Fix: Brizy pages initially not showing any content.
=> chore: changelog updated

inc/assets/css/admin.css
When we click on Import button - Template doesn't appear in the background - https://a.cl.ly/X6ueOngn
=> fix: template preview vanish during import

inc/assets/js/admin-page.js
3. I can see the form on single page import - https://a.cl.ly/ApuYjPQO Does we do ?? I have subscribed on Import Complete Site but again I can see popup on single page import
---
Test Case -
1. Install Free Starter Templates on a fresh setup
2. Import Outdoor Adventure Template 
3. Submit the subscription form and complete the importing.
3. Once the import is completed click on a single page import without refreshing the page.
4. During single page import, it should not ask for the subscription form again.
=> ST-183 - fix: subscription form shows again once subscribed

inc/importers/batch-processing/class-astra-sites-batch-processing-gutenberg.php
Test Case -
1. Import the Outdoor Adventure template and check the contact page in the frontend.
2. Previously it was not showing the form and now this PR fixes the same.
=> fix:contact forms in gutenberg template

inc/assets/js/admin-page.js
Test Case - 
1. Import outdoor adventure template and then without refresh import single page.
2. Delete previous site option should no show for a single page import
=> fix: hide delete previous site option on single page import

.github/workflows/push-asset-readme-update.yml.yml, .github/workflows/push-to-deploy.yml
Use upstream repo instead of using forked GitHub actions.
We were using forked actions in #136 for one bug fix that was not included in upstream.
=> use actions from 10up instead of using the forked actions

README.md, inc/lib/ast-block-templates/ast-block-templates.php, inc/lib/ast-block-templates/classes/class-ast-block-templates.php, inc/lib/ast-block-templates/version.json, readme.txt
Updated the Gutenberg Templates v1.0.8 with below changes:
```
v1.0.8 - 22-June-2021
- Improvement: Avoided loading the Gutenberg Blocks scripts in the customizer screen.
```
=> Updated Gutenberg Templates v1.0.8

inc/importers/batch-processing/class-astra-sites-batch-processing-elementor.php
Contact form not visible if widgets are used in elementor
Bug fix (non-breaking change which fixes an issue) 
Import `Tech Blogger` and check for a contact form on the Contact page.
=> ST-286- fix: contact form not visible if widgets are used in elementors

composer.json, inc/classes/class-astra-sites.php, inc/lib/onboarding/assets/src/steps/customize-site/customize-steps/license-validation/controls.js, inc/lib/onboarding/assets/src/steps/customize-site/customize-steps/license-validation/index.js
1. When the white label is enabled and starter template details added we are disabled promotes Essential & Growth bundle.
2.  If the agency URL is present then we add that URL to the 'unlock access' button if empty then we add "#" on the link.
3. We only displayed unlock button on the page if while the label was enabled and starter template details were added.
Task link: https://brainstormforce.atlassian.net/browse/STAR-45
https://d.pr/v/YgRds0
https://d.pr/v/ysAdf7
Improvement
1. install/active  astra add on and enabled whileleble option
2. Add starter template details when enabled white lable.
3. IF agency link URL then you see the link on unlock access button
4. IF not link then  # on button link.
=> When whitelabel option is enabled it disabled  promotes Essential & Growth bundle

composer.json, inc/importers/batch-processing/class-astra-sites-batch-processing.php, inc/lib/onboarding/class-onboarding-loader.php
**Issue**
The starter template gives no template suggestion after selecting the page builder.
**When you install the Astra theme and Starter template for the first time, after the starter template is activated, it redirects you to the Site creation wizard. After that, you click on build your site > Select a page builder, and after on the page where it should list the templates, there are no suggestions of any templates at all.** 
https://monosnap.com/file/1ZdGDQ9N3Z62s8xagxZdfvgqdpwb0X
Task:  https://brainstormforce.atlassian.net/browse/STAR-44
**Fixed:**
After activating the starter template from Astra noticed for the first time.
https://d.pr/v/14fpJ4
https://d.pr/v/14fpJ4
Bug fix (non-breaking change which fixes an issue)
=> Manage sequence for initial ST load while install/active from Astra notice

inc/classes/class-astra-sites-white-label.php
- With Astra's 4.0 we are introducing new dashboard
- And as per review, we decided to update position of Astra toplevel menu position when ST plugin being activated
- https://share.bsf.io/GGuJL6or
- New feature (non-breaking change )
- Check with Astra's 4.0 version
- Enable this ST plugin 
- Menu position should update from above appearance to next dahboard
=> refactor: Astra's 4.0 dashboard app menu's position updated as per review

inc/lib/onboarding/assets/src/steps/site-list/index.js, inc/lib/onboarding/assets/src/utils/functions.js
This PR addresses the issue by implementing the display of the 'Premium' badge and the 'Premium' filter for Gutenberg/Spectra premium templates.
https://d.pr/v/UjTFvr
=> STAR-136: Add 'Premium' Badge and Filter for Gutenberg/Spectra Premium Templates
